export const ART_TYPES: string[] = [
    "Photography",
    "Landscape Photography",
    "Portrait Photography",
    "Street Photography",
    "Astrophotography",
    "Architectural Photography",
    "Macro Photography",
    "Fashion Photography",
    "Photojournalism",
    "Graphic Design",
    "Illustration",
    "Digital Art",
    "3D Art",
    "Concept Art",
    "Painting",
    "Oil Painting",
    "Acrylic",
    "Watercolor",
    "Mixed Media",
    "Sculpture",
    "Ceramics",
    "Installation Art",
    "Typography",
    "Calligraphy",
    "Lettering",
    "Printmaking",
    "Animation",
    "Motion Graphics",
    "UI/UX Design",
    "Product Design",
    "Textile Art",
    "Fiber Art",
    "Street Art",
    "Mural",
    "Collage",
    "Photomanipulation",
    "Other"
];
