export const LABELS = {
    STUDIO: 'Studio',
    STUDIOS: 'Studios',
    GALLERY: 'Gallery',
    GALLERIES: 'Galleries',
};

export const FEATURE_LABELS = {
    COLLABORATIVE_SPACE: LABELS.STUDIO,
    COLLABORATIVE_SPACES: LABELS.STUDIOS,
    PURCHASED_PRINTS: LABELS.GALLERY,
    PURCHASED_PRINTS_PLURAL: LABELS.GALLERIES,
};
